### ISSUE TITLE
Issue Number 2- what I have isn't working. is there another way?

### ISSUE THREAD

**Issue by opemily** [opemily/serial-killer-concentration#2]
What feature are you working on?

Getting the two cards to recognize they are a match.

If you are encountering a technical difficulty:
What error are you getting?
What have you attempted to fix your error?
A link to a line number in your application code and/or a code snippet where you think the error is occurring.
If it is a conceptual or architectural issue:
Describe the conundrum

I've been using an if else statement but even if the  two items are a match it refuses to recognize. Also the second card doesn't have a chance to flip over. 
 
Explain the possible paths you have explored

Reading on stackoverflow, jquery.com and websites. Asked the group for help but no one answered

**Comment by annarankin** [comment]
Hey Emily! I'm not sure exactly what you mean - can you describe the second issue a little more thoroughly and link me to where in your code the issue is occurring?

**Comment by opemily** [comment]
firstClick = function (e) {
     firstDivClick = $(e.target);

    $(e.target).removeClass('covered');
    $('.covered').off('click', firstClick);
    $('.covered').on('click', secondClick);
  };


// Second click should check if the classes match. If they do a modal should appear containing the blurb about the serial killer. If not both should be rehidden.

  secondClick = function (e) {
    secondDivClick = $(e.target);

    $(e.target).removeClass('covered');

     if (firstDivClick === secondDivClick) {
        $('.modal').removeClass('hidden');
       matchCounter++;
    } else {
         firstDivClick.addClass('covered');
       secondDivClick.addClass('covered');
   }

    $('.covered').off('click', secondClick);
    $('.covered').on('click', firstClick);
   
  };

When I select the first div it stores its information in the variable firstDivClick, when I click the secondDiv it stores it in secondDivClick. What I want to do is compare firstDivClick and secondDivClick to see if they are the same (or at least have the same second class). I also want to create a delay before I compare so the user has the ability to see what the second Div looks like (it immediately covers up). IS there a better way to do it then the way I'm currently doing it.

**Comment by annarankin** [comment]
Hey Emily, what happens when you console log `firstDiv` and `secondDiv`? What are you expecting/comparing?

**Comment by opemily** [comment]
firstDivClick
[<div class=​"square ed-gein">​</div>​]
secondDivClick
[<div class=​"square david-berkowitz">​</div>​]

**Comment by opemily** [comment]
firstDivClick
div class=​"square ed-gein"​
secondDivClick
div class=​"square david-berkowitz​"

**Comment by opemily** [comment]
sorry the first time I wrote it it hid the items

**Comment by opemily** [comment]
Phil- can you help?

**Comment by phlco** [comment]
Hi Emily, how are you planning on comparing the divs?  From the code snippet I don't entirely see what the shared value would be?

It looks like you assign the first clicked `div` to a variable and then the second clicked `div` to another variable.  The comparison operator won't work on whole objects.

For instance:

```js
var a = {name: "Aziz"};
var b = {name: "Aziz"};
```

These look like the "same" object to us so they should be "equal" but they're two unique things. 

```
a === b // false
```

What we can compare is a primitive value, like a string or number.

```
a.name === b.name // true
```

Does that help at all?

**Comment by opemily** [comment]
I might have come up with something. I am extracting the classes from the saved click and them comparing them

**Comment by opemily** [comment]
How do I keep the divs from immediately closing?
